name = "packtracker"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".vercel/output/static/_worker.js/index.js"

[assets]
directory = ".vercel/output/static"

[vars]
NEXT_PUBLIC_APP_URL = "https://trackflow.cz"
